import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting coder</h1>
        <div className={styles.imagewrap}>
          <img
            className={styles.myImg}
            src="/homeImg.avif"
            width={237}
            height={185}
          />
        </div>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder.
        </p>
        <h2>Popular Blogs</h2>
        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn javascript int 2022</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript int 2022</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript int 2022</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
        </div>
      </main>
    </div>
  );
}
