import Head from "next/head";
import styles from "../styles/Home.module.css";
import * as fs from "fs";
import Link from "next/link";
export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <img
            className={styles.myImg}
            src="/homeImg.avif"
            width={237}
            height={158}
            alt="hunting coder"
          />
        </div>
        <h1 className={styles.title}>
          {" "}
          <span className="dummy">&lt;HuntingCoder/&gt;</span>
        </h1>

        <div className={styles.blogMain}>
          {props.allBlogs.map((blogitem) => {
            return (
              <div key={blogitem.slug}>
                <Link href={`/blogpost/${blogitem.slug}`}>
                  <h3 className={styles.blogItemh3}>{blogitem.title}</h3>
                </Link>
                <p className={styles.blogItemp}>
                  {blogitem.metadesc.substr(0, 140)}...
                </p>
                <Link href={`/blogpost/${blogitem.slug}`}>
                  <button className={styles.btn}>Read More</button>
                </Link>
              </div>
            );
          })}
        </div>

        <div>
          <Link href="/blog">
            <p className={styles.readMore}>More Blogs &gt;&gt;</p>
          </Link>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  let data = await fs.promises.readdir("blogdata");

  let myfile;
  let allBlogs = [];
  for (let index = 0; index < 2; index++) {
    const item = data[index];
    myfile = await fs.promises.readFile("blogdata/" + item, "utf-8");
    allBlogs.push(JSON.parse(myfile));
  }

  return {
    props: { allBlogs },
  };
}
